name: Calculator Test By Python

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set python version 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest

    
    - name: Run unit tests
      run: python -m unittest discover

    - name: Coverage report
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report

      
    - name: done successfully
      run: echo "done successfully"
