name: Calculator Test By Python

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set python version 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: run calculator
      run: python calculator.py add 5 3
      
    - name: done successfully
      run: echo "done successfully"
